[package]
name = "seacatering-be"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio", "macros"] }
serde = { version = "1", features = ["derive"] }
argon2 = "0.5"
uuid = { version = "1", features = ["v4"] }
